version: '3.1'

services:
  joomla:
    image: joomla:php8.1-apache
    restart: always
    links:
      - joomladb:mysql
    ports:
      - 8080:80
    volumes:
      - "./joomla:/var/www/html"
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: megapass

  joomladb:
    image: mysql
    ports:
      - 3306
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: megapass
