roles:
  - name: geerlingguy.firewall
  - name: geerlingguy.docker
  - name: geerlingguy.pip

collections:
  - name: ansible.posix
  - name: community.crypto
  - name: community.general
  - name: community.docker
